<<<<<<< HEAD
# Generated by Django 3.2.16 on 2023-01-04 14:21

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 5.1.5 on 2025-01-21 18:02

import django.db.models.deletion
from django.db import migrations, models
>>>>>>> b5b3d533ad28d280a2ed2a7679527113b8de704b


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=256)),
<<<<<<< HEAD
                ('slug', models.SlugField(max_length=64)),
=======
                ('slug', models.SlugField(max_length=64, unique=True)),
>>>>>>> b5b3d533ad28d280a2ed2a7679527113b8de704b
                ('output_order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=256)),
<<<<<<< HEAD
                ('slug', models.SlugField(max_length=64)),
=======
                ('slug', models.SlugField(max_length=64, unique=True)),
>>>>>>> b5b3d533ad28d280a2ed2a7679527113b8de704b
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wrapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True)),
                ('is_on_main', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
<<<<<<< HEAD
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ice_creams', to='ice_cream.category')),
                ('toppings', models.ManyToManyField(to='ice_cream.Topping')),
                ('wrapper', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ice_cream', to='ice_cream.wrapper')),
=======
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ice_cream.category')),
                ('toppings', models.ManyToManyField(to='ice_cream.topping')),
                ('wrapper', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ice_cream.wrapper')),
>>>>>>> b5b3d533ad28d280a2ed2a7679527113b8de704b
            ],
            options={
                'abstract': False,
            },
        ),
<<<<<<< HEAD
    ]
=======
    ]
>>>>>>> b5b3d533ad28d280a2ed2a7679527113b8de704b
